language: groovy

jdk:
    - oraclejdk7

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/grails_inline.sh

install:
    - make_inline_dependency ../transmart-java
    - make_inline_dependency ../biomart-domain

script:
    - grails package --non-interactive --stacktrace
